/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdvisorsRouteImport } from './routes/advisors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalJourneyRouteImport } from './routes/portal.journey'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalInsightsRouteImport } from './routes/portal.insights'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalComplianceRouteImport } from './routes/portal.compliance'
import { Route as PortalCompaniesRouteImport } from './routes/portal.companies'
import { Route as PortalAppointmentsRouteImport } from './routes/portal.appointments'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsRoute = AdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalJourneyRoute = PortalJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInsightsRoute = PortalInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalComplianceRoute = PortalComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCompaniesRoute = PortalCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAppointmentsRoute = PortalAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisors': typeof AdvisorsRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/journeys': typeof JourneysRoute
  '/portal': typeof PortalRouteWithChildren
  '/services': typeof ServicesRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/companies': typeof PortalCompaniesRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/insights': typeof PortalInsightsRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/journey': typeof PortalJourneyRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisors': typeof AdvisorsRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/journeys': typeof JourneysRoute
  '/services': typeof ServicesRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/companies': typeof PortalCompaniesRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/insights': typeof PortalInsightsRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/journey': typeof PortalJourneyRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisors': typeof AdvisorsRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/journeys': typeof JourneysRoute
  '/portal': typeof PortalRouteWithChildren
  '/services': typeof ServicesRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/companies': typeof PortalCompaniesRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/insights': typeof PortalInsightsRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/journey': typeof PortalJourneyRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisors'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/industries'
    | '/insights'
    | '/journeys'
    | '/portal'
    | '/services'
    | '/portal/appointments'
    | '/portal/companies'
    | '/portal/compliance'
    | '/portal/documents'
    | '/portal/insights'
    | '/portal/invoices'
    | '/portal/journey'
    | '/portal/messages'
    | '/portal/profile'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisors'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/industries'
    | '/insights'
    | '/journeys'
    | '/services'
    | '/portal/appointments'
    | '/portal/companies'
    | '/portal/compliance'
    | '/portal/documents'
    | '/portal/insights'
    | '/portal/invoices'
    | '/portal/journey'
    | '/portal/messages'
    | '/portal/profile'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisors'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/industries'
    | '/insights'
    | '/journeys'
    | '/portal'
    | '/services'
    | '/portal/appointments'
    | '/portal/companies'
    | '/portal/compliance'
    | '/portal/documents'
    | '/portal/insights'
    | '/portal/invoices'
    | '/portal/journey'
    | '/portal/messages'
    | '/portal/profile'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisorsRoute: typeof AdvisorsRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  GalleryRoute: typeof GalleryRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRoute
  JourneysRoute: typeof JourneysRoute
  PortalRoute: typeof PortalRouteWithChildren
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors': {
      id: '/advisors'
      path: '/advisors'
      fullPath: '/advisors'
      preLoaderRoute: typeof AdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/journey': {
      id: '/portal/journey'
      path: '/journey'
      fullPath: '/portal/journey'
      preLoaderRoute: typeof PortalJourneyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/insights': {
      id: '/portal/insights'
      path: '/insights'
      fullPath: '/portal/insights'
      preLoaderRoute: typeof PortalInsightsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/compliance': {
      id: '/portal/compliance'
      path: '/compliance'
      fullPath: '/portal/compliance'
      preLoaderRoute: typeof PortalComplianceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/companies': {
      id: '/portal/companies'
      path: '/companies'
      fullPath: '/portal/companies'
      preLoaderRoute: typeof PortalCompaniesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/appointments': {
      id: '/portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalAppointmentsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAppointmentsRoute: typeof PortalAppointmentsRoute
  PortalCompaniesRoute: typeof PortalCompaniesRoute
  PortalComplianceRoute: typeof PortalComplianceRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalInsightsRoute: typeof PortalInsightsRoute
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalJourneyRoute: typeof PortalJourneyRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAppointmentsRoute: PortalAppointmentsRoute,
  PortalCompaniesRoute: PortalCompaniesRoute,
  PortalComplianceRoute: PortalComplianceRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalInsightsRoute: PortalInsightsRoute,
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalJourneyRoute: PortalJourneyRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisorsRoute: AdvisorsRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  GalleryRoute: GalleryRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRoute,
  JourneysRoute: JourneysRoute,
  PortalRoute: PortalRouteWithChildren,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
